### PR TITLE
Rewrite using HarmonyLib to patch the player movement

### PR DESCRIPTION
**Pull request by Crylion**
This is the polished version of my test branch for actually forced movement of the player model.
Splitting the movement over more updates seems to have made phasing through walls unlikely enough (at least for >= 60fps) and the mod continues to honor the "stop movement" button of the game.
The values of the dash are obviously very open for discussion 😁

Please give it a try when you got the time :)

### CODE REVIEW

**Comment by propstg** [comment]
I haven't had a chance to test this out yet, but if I'm reading this correctly, the dashing effect (whether stationary or in motion) will be caused purely by the force, and the player's speed will not be altered?  If so, that's an exciting change, because it seems like it will make the mod completely compatible with mods that also set the speed, like PrepGhost and Custom Difficulty.

I am curious if the mod _needed_ to be rewritten back into a harmony patch? I have been trying to avoid adding new ones, where I can, since the game's developer seems to have a preference against them. :D

**Comment by Crylion** [comment]
That's correct, the dash only applies force to the player model now, using an appropriate fraction of the speed over a smaller amount of time.

This is (basically) the code of the game, while the player moves:
```
Vector3 force = base.transform.forward * (speed * Time.deltaTime);
force.y = 0f;
Rigidbody.AddForce(force);
```

I do the same, just with different values over a dash period.

And you are right, I can certainly see why the devs would be cautious about multiple people patching the same method potentially 🤔 
I think I could theoretically change it, so I only use the patch to get a reference to the Rigidbody instances. The rest of the code could be outside the patch method to keep it to a minimum.
If you know of another way to access 1 or 2 private members of the PlayerView, I'm all ears :D

**Comment by propstg** [comment]
That's very cool! Thanks for the explanation.

You _should_ be able to get access to the field using reflection. Granted, this is also not ideal, but since the modding API is still a WIP, I would prefer to do what is possible within the API now and hope it becomes less hacky over time.

Here's a working example of using reflection to get a field from the PlayerView: https://github.com/propstg/plateup-dash-ping/blob/master/DashPing/Main.cs#L84-L85 ReflectionUtils is a KitchenLib util that caches the reflection lookups, so at least the performance penalty from getting the FieldInfo is only incurred once. I haven't tried it for the rigid body, but I suspect it would be basically the same?

**Comment by propstg** [comment]
I made an unlisted mod with this branch, for testing purposes: https://steamcommunity.com/sharedfiles/filedetails/?id=2934515272

**Comment by Crylion** [comment]
> Here's a working example of using reflection to get a field from the PlayerView: https://github.com/propstg/plateup-dash-ping/blob/master/DashPing/Main.cs#L84-L85 ReflectionUtils is a KitchenLib util that caches the reflection lookups, so at least the performance penalty from getting the FieldInfo is only incurred once. I haven't tried it for the rigid body, but I suspect it would be basically the same?

🤦 I even looked at ReflectionUtil, but couldn't quite figure out how it worked at the moment, and then forgot about it again xD
You are right, that should work just as well. I'm sure I could test that out this weekend.
And I still learned a lot, playing around with the HarmonyPatch 😁

**Comment by Crylion** [comment]
Now that I had some time and felt well enough to do some fiddling around with the code, it was actually pretty easy to do this with the reflection util 🙈 

It now seems to work just as it did with the harmony patch, but without patching anything :)

**Comment by propstg** [comment]
Good job! Looks great.

I've been using the unlisted mod and haven't noticed anything too wild (aside from going through a couple walls unexpectedly :joy:) I'm going to go ahead and merge this and update the unlisted mod tonight. Then I'll probably update the actual mod in a day or two. I'll tag you in the modding discord when it's released. Thanks!

**Pull request merged**
